feat: override dtk's blur
linuxdeepin/treeland pull request #103
Opened 2024-01-10 06:21 UTC by 18202781743

it exists some bug in treeland, so we override dtkdeclarative's
blur.
  It depends on https://github.com/linuxdeepin/dtkdeclarative/pull/274

2024-01-10 06:38 UTC, 18202781743 commented
@zccrs

2024-01-10 08:23 UTC, zccrs requested changes

2024-01-10 08:23 UTC, zccrs commented on src/treeland/InWindowBlur.qml
> +    property int radius
real

2024-01-10 08:23 UTC, zccrs commented on src/treeland/InWindowBlur.qml
> +    property alias offscreen: blitter.offscreen
这应该决定 blur 的 visible

2024-01-10 08:23 UTC, zccrs commented on src/treeland/InWindowBlur.qml
> +    default property alias blurChildren: blitter.children
default property alias data  : blitter.data

2024-01-10 12:50 UTC, 18202781743 commented on src/treeland/InWindowBlur.qml
> +    property alias offscreen: blitter.offscreen
这个跟dtk里的接口保持一致，dtk里有个offscreen,它不是blur的visible吧，

2024-01-10 12:50 UTC, 18202781743 commented on src/treeland/InWindowBlur.qml
> +    default property alias blurChildren: blitter.children
这里应该不是default吧，否则都放到blit内部了，

2024-01-12 05:08 UTC, justforlxz approved these changes

2024-01-15 09:18 UTC, zccrs requested changes

2024-01-15 09:18 UTC, zccrs commented on src/treeland/InWindowBlur.qml
> +    property real radius
可以使用 alias

2024-01-15 09:18 UTC, zccrs commented on src/treeland/InWindowBlur.qml
> +    Item {
这是做什么？

2024-01-16 02:00 UTC, zccrs requested changes

2024-01-16 02:00 UTC, zccrs commented on src/treeland/InWindowBlur.qml
> +        offscreen: false
不要设置

2024-01-16 02:00 UTC, zccrs commented on src/treeland/InWindowBlur.qml
> +
default 属性为什么去掉了？

2024-01-16 03:43 UTC, zccrs approved these changes

2024-01-16 07:13 UTC, merged