feat: optimize decoration and background
linuxdeepin/treeland pull request #170
Opened 2024-03-08 07:33 UTC by Groveer

2024-03-13 03:28 UTC, wineee requested changes

2024-03-13 03:28 UTC, wineee commented on src/treeland/quick/qml/StackWorkspace.qml
> +                visible: personalizationMapper.backgroundType == 2
Make this enum type available in qml, don't use int

2024-03-13 09:30 UTC, justforlxz submitted a review, later dismissed

2024-03-13 09:31 UTC, justforlxz submitted a review, later dismissed

2024-03-21 07:26 UTC, justforlxz approved these changes

2024-03-21 07:26 UTC, merged