feat: window default position
linuxdeepin/treeland pull request #233
Opened 2024-05-14 12:18 UTC by justforlxz

change to output center

Closed: https://github.com/linuxdeepin/treeland/issues/232

Log: 默认窗口出现在屏幕中间

2024-05-14 12:28 UTC, wineee requested changes

2024-05-14 12:28 UTC, wineee commented on src/treeland/quick/qml/StackWorkspace.qml
>                                      + Helper.getLeftExclusiveMargin(waylandSurface)
这个不应该保留了，在正中间比较好看

2024-05-14 12:46 UTC, justforlxz commented on src/treeland/quick/qml/StackWorkspace.qml
>                                      + Helper.getLeftExclusiveMargin(waylandSurface)
可以

2024-05-15 02:06 UTC, wineee approved these changes

2024-05-16 03:45 UTC, merged