feat: Implement window_management_v1 functions
linuxdeepin/treeland pull request #291
Opened 2024-06-07 05:44 UTC by Dami-star

Implementing desktop preview

2024-06-12 03:32 UTC, zccrs requested changes

2024-06-12 03:32 UTC, zccrs commented on src/qml/StackWorkspace.qml
> +        visible: !multitaskView.active || (treelandWindowManagement.desktopState == 2)
怎么不用枚举呢？

2024-06-12 03:41 UTC, zccrs requested changes

2024-06-12 03:41 UTC, zccrs commented on src/modules/treeland-window-management/protocols/treeland_window_management_v1.xml
> +  <event name="show_desktop_changed">
遵循下wayland event的命名风格，我记得没用过 _changed 这种后缀。

2024-06-12 03:41 UTC, zccrs commented on src/modules/treeland-window-management/protocols/treeland_window_management_v1.xml
> +    <entry name="preview" value="2"/>
为什么需要 "preview" 模式呢？理论上 show_desktop 行为是可以恢复的，如果需要 preview，可以在进入 show_desktop 状态后再恢复即可。

2024-06-12 03:41 UTC, zccrs commented on src/modules/treeland-window-management/protocols/treeland_window_management_v1.xml
> +    <entry name="disabled" value="0"/>
不建议用 disabled enabled 这类枚举，容易被误解为禁用了 show_desktop 功能。
本质上，控制是否“显示桌面”的功能是针对工作区里的 xdg 、xwayland 窗口的，可以把这个协议设计成是对工作区相关功能的封装，这样的话 `show_desktop` 可能就是某个工作区的一种状态而已。举例：

````
enum WorkspaceState {
    Normal,
    ShowDesktop
}
````

2024-06-12 03:41 UTC, zccrs commented on src/modules/treeland-window-management/protocols/treeland_window_management_v1.xml
> +  <request name="destroy" type="destructor">
协议对象的销毁都需要自己在协议里加个 destroy 的 request 吗？理论上应该直接销毁 wayland 的 wl_resource 资源，在 compositor 那端就知道了。

2024-06-12 11:06 UTC, Dami-star commented on src/qml/StackWorkspace.qml
> +        visible: !multitaskView.active || (treelandWindowManagement.desktopState == 2)
done

2024-06-12 11:06 UTC, Dami-star commented on src/modules/treeland-window-management/protocols/treeland_window_management_v1.xml
> +  <event name="show_desktop_changed">
done

2024-06-12 11:07 UTC, Dami-star commented on src/modules/treeland-window-management/protocols/treeland_window_management_v1.xml
> +    <entry name="preview" value="2"/>
done

2024-06-12 11:07 UTC, Dami-star commented on src/modules/treeland-window-management/protocols/treeland_window_management_v1.xml
> +    <entry name="disabled" value="0"/>
done

2024-06-12 11:08 UTC, Dami-star commented on src/modules/treeland-window-management/protocols/treeland_window_management_v1.xml
> +  <request name="destroy" type="destructor">
根据目前查看都需要客户端保留destroy 的 request

2024-06-17 08:27 UTC, justforlxz approved these changes

2024-06-18 06:34 UTC, wineee requested changes

2024-06-18 06:34 UTC, wineee commented on src/qml/StackWorkspace.qml
> +
```suggestion
```

2024-06-18 06:34 UTC, wineee commented on src/qml/StackToplevelHelper.qml
> +            }
封装成一个函数，cancelMinimize 也在调用

2024-06-18 06:34 UTC, wineee commented on src/modules/treeland-window-management/windowmanagement.h
> +#include <qwsignalconnector.h>
```suggestion
```

2024-06-18 06:34 UTC, wineee commented on src/modules/treeland-window-management/windowmanagement.h
> +    enum DesktopState { Normal, Show, Preview };
```suggestion
    enum class DesktopState { Normal, Show, Preview };
```

2024-06-18 11:40 UTC, Dami-star commented on src/qml/StackWorkspace.qml
> +
done

2024-06-18 11:40 UTC, Dami-star commented on src/qml/StackToplevelHelper.qml
> +            }
done

2024-06-18 11:40 UTC, Dami-star commented on src/modules/treeland-window-management/windowmanagement.h
> +#include <qwsignalconnector.h>
done

2024-06-18 11:41 UTC, Dami-star commented on src/modules/treeland-window-management/windowmanagement.h
> +    enum DesktopState { Normal, Show, Preview };
done, 建议现存类似写法也都修改下

2024-06-19 02:50 UTC, wineee requested changes

2024-06-19 02:50 UTC, wineee commented on src/modules/treeland-window-management/impl/window_management_impl.cpp
> +    wl_global_destroy(global);
```suggestion
if (global)
    wl_global_destroy(global);
```

2024-06-19 02:50 UTC, wineee commented on src/modules/treeland-window-management/impl/window_management_impl.cpp
> +
```
    if (!manager->global) {
        delete manager;
        return nullptr;
    }
```

2024-06-19 02:50 UTC, wineee commented on src/modules/treeland-window-management/impl/window_management_impl.h
> +    wl_global *global;
```suggestion
    wl_global *global{ nullptr };
```

2024-06-19 03:04 UTC, Dami-star commented on src/modules/treeland-window-management/impl/window_management_impl.cpp
> +    wl_global_destroy(global);
done

2024-06-19 03:04 UTC, Dami-star commented on src/modules/treeland-window-management/impl/window_management_impl.cpp
> +
done

2024-06-19 03:04 UTC, Dami-star commented on src/modules/treeland-window-management/impl/window_management_impl.h
> +    wl_global *global;
done

2024-06-19 03:16 UTC, wineee requested changes

2024-06-19 03:16 UTC, wineee commented on src/qml/StackToplevelHelper.qml
> +                setAllSurfacesVisble(false)
不应该是 setVisble false， 而是申请最小化吧？

2024-06-19 03:30 UTC, Dami-star commented on src/qml/StackToplevelHelper.qml
> +                setAllSurfacesVisble(false)
这里是显示桌面流程被破坏，例如新打开一个窗口时，破坏显示桌面流程，其他窗口仍然visable false,只有新打开的窗口正常显示，与x11 下目前保持一样的效果

2024-06-19 03:35 UTC, Dami-star commented on src/qml/StackToplevelHelper.qml
> +                setAllSurfacesVisble(false)
设置treelandWindowManagement.desktopState 是先退出显示桌面流程，再去设置其他surface窗口

2024-06-19 03:37 UTC, wineee commented on src/qml/StackToplevelHelper.qml
> +                setAllSurfacesVisble(false)
其他窗口应该最小化而不是visable false吧，显示桌面新打开一个窗口后，其他窗口用户可以取消最小化使其显示出来。如果 visable false，你什么时候改成 true 呢？

2024-06-19 06:22 UTC, Dami-star commented on src/qml/StackToplevelHelper.qml
> +                setAllSurfacesVisble(false)
那只能将显示桌面和预览桌面实现分开处理了，显示桌面再修改下实现

2024-06-19 09:11 UTC, wineee submitted a review, later dismissed
暂定最小化相关逻辑后续再优化

2024-06-20 06:41 UTC, zccrs commented
+1 协议的定义我这里没啥问题了，其他方面没有判断

2024-06-20 08:16 UTC, zccrs approved these changes

2024-06-20 09:15 UTC, merged