fix: when output_name is empty, set all screen background
linuxdeepin/treeland pull request #297
Opened 2024-06-14 02:52 UTC by zorowk

2024-06-20 10:03 UTC, justforlxz submitted a review, later dismissed

2024-06-21 02:48 UTC, wineee requested changes

2024-06-21 02:48 UTC, wineee commented on src/modules/treeland-personalization-manager/personalizationmanager.cpp
> +            context->output_name = strdup(screen->name().toLocal8Bit().data());
```suggestion
            context->output_name =  screen->name();
```

2024-06-24 07:20 UTC, Groveer submitted a review, later dismissed

2024-06-24 07:25 UTC, wineee commented on src/modules/treeland-personalization-manager/personalizationmanager.cpp
> +        Q_FOREACH (QScreen *screen, QGuiApplication::screens()) {
Note: Since Qt 5.7, the use of this macro is discouraged. Use C++11 range-based for, possibly with std::as_const(), as needed.

2024-06-24 07:30 UTC, wineee commented on src/modules/treeland-personalization-manager/personalizationmanager.cpp
> +        Q_FOREACH (QScreen *screen, QGuiApplication::screens()) {
for (QScreen *screen : QGuiApplication::screens())

2024-06-24 07:38 UTC, wineee approved these changes

2024-06-24 07:51 UTC, merged