feat: impl userList
linuxdeepin/treeland pull request #32
Opened 2023-11-30 09:55 UTC by ComixHe

update waylib

2023-11-30 10:00 UTC, wineee requested changes

2023-11-30 10:00 UTC, wineee commented on src/greeter/UserModel.cpp
> -* Copyright (c) 2013 Abdurrahman AVCI <abdurrahmanavci@gmail.com>
Original copyright information should not be deleted

2023-12-06 01:44 UTC, ComixHe commented
/check obs

2023-12-06 09:14 UTC, justforlxz approved these changes

2023-12-08 09:27 UTC, justforlxz approved these changes

2023-12-08 09:27 UTC, merged