feat: add decoration global menu
linuxdeepin/treeland pull request #328
Opened 2024-06-24 08:58 UTC by zorowk

2024-06-24 09:06 UTC, Groveer approved these changes

2024-06-24 09:11 UTC, justforlxz approved these changes

2024-06-24 09:21 UTC, wineee requested changes

2024-06-24 09:21 UTC, wineee commented on src/qml/WindowMenu.qml
> +// Copyright (C) 2023 JiDe Zhang <zccrs@live.com>.
Copyright？

2024-06-24 09:47 UTC, wineee commented on CMakeLists.txt
> +set(WITH_SUBMODULE_QWLROOTS ON)
why ?

2024-06-25 01:10 UTC, Groveer approved these changes

2024-06-25 08:33 UTC, merged