feat: add wallpaper protocol
linuxdeepin/treeland pull request #34
Opened 2023-12-05 05:17 UTC by zorowk

Log: add wallpaper protocol

2023-12-06 06:53 UTC, justforlxz requested changes

2023-12-06 06:53 UTC, justforlxz commented on src/treeland/protocols/personalization_manager_impl.cpp
> +    }
删除

2023-12-06 06:53 UTC, justforlxz commented on src/treeland/protocols/personalization_manager_impl.cpp
> +}
产生 context 对象只能在 create_wallpaper_context_listener 中

2023-12-06 06:53 UTC, justforlxz commented on src/treeland/protocols/personalization_manager_impl.cpp
> +    }
不做这件事

2023-12-06 06:53 UTC, justforlxz commented on src/treeland/protocols/personalization_manager_impl.h
> +// Copyright (C) 2023 WenHao Peng <near.kingzero@gmail.com>.
用公司的邮箱

2023-12-06 06:53 UTC, justforlxz commented on src/treeland/protocols/personalizationmanager.h
> +    void requestWallpaperContext(TreeLandWallpaperContext *context);
wallpaperContextCreated

2023-12-12 02:41 UTC, wineee requested changes

2023-12-12 02:41 UTC, wineee commented on src/treeland/treeland-fake-session/fake-session.cpp
> +#include <QtWaylandClient/6.6.1/QtWaylandClient/private/qwaylandwindow_p.h>
不要写死 6.6.1 目录，看看cmake提供的路径，<QtWaylandClient/private/qwaylandwindow_p.h> 应该可以

2023-12-12 05:17 UTC, justforlxz requested changes

2023-12-12 05:17 UTC, justforlxz commented on src/treeland/protocols/personalization_manager_impl.cpp
> +    wl_list_remove(wl_resource_get_link(resource));
```suggestion
    struct *context = personalization_window_context_from_resource(resource);

    wl_signal_emit_mutable(&context->events.destroy, context);

    wl_list_remove(wl_resource_get_link(resource));

    free(context);
```

2023-12-12 05:17 UTC, justforlxz commented on src/treeland/protocols/personalization_manager_impl.cpp
> +void personalization_window_context_v1_destroy(
删除

2023-12-12 05:17 UTC, justforlxz commented on src/treeland/protocols/personalization_manager_impl.h
> +void personalization_window_context_v1_destroy(
删除

2023-12-12 05:30 UTC, zorowk commented
I have read the CLA Document and I hereby sign the CLA.

2023-12-12 05:31 UTC, justforlxz approved these changes

2023-12-12 05:31 UTC, merged