Improve Tinywl's TiledLayout
linuxdeepin/treeland pull request #356
Opened 2024-09-30 09:33 UTC by LittFlower

2024-10-11 06:33 UTC, wineee requested changes

2024-10-11 06:33 UTC, wineee commented on src/qml/HorizontalLayout.qml
> +    property XdgSurfaceItem currentSurfaceItem: null
使用基类 Item 而非 XdgSurfaceItem，方便扩展 xwayland 支持

2024-10-11 06:33 UTC, wineee commented on src/utils/helper.cpp
> +    //     if (!m_actions.empty() && !m_currentUser.isEmpty()) {
无用代码清理一下

2024-10-11 06:33 UTC, wineee commented on src/utils/helper.cpp
> -    if (moveReiszeState.surfaceItem
这些逻辑不要删除，堆叠需要，平铺不会调用这里就行

2024-10-13 13:29 UTC, LittFlower commented on src/qml/HorizontalLayout.qml
> +    property XdgSurfaceItem currentSurfaceItem: null
已修复

2024-10-13 13:36 UTC, LittFlower commented on src/utils/helper.cpp
> +    //     if (!m_actions.empty() && !m_currentUser.isEmpty()) {
已清理

2024-10-24 02:18 UTC, wineee requested changes

2024-10-24 02:18 UTC, wineee commented on src/utils/helper.cpp
> +        printf("modifiers: %d, key: %d\n", modifiers, key);
用 qInfo

2024-10-24 02:18 UTC, wineee commented on src/utils/helper.cpp
> +                emit switchLayout();
emit 都用 Q_EMIT, treeland 不使用小写 Qt 关键字，防止和其他项目冲突
比如 signal 在 wlroots 可能是变量名，因此只用 Q_SIGNALS

2024-10-24 02:18 UTC, wineee commented on src/utils/helper.cpp
> +                printf("undefined modifiers: %d, key: %d\n", modifiers, key);
这里不要打印

2024-10-24 02:18 UTC, wineee commented on src/qml/VerticalLayout.qml
> +        // for (let i = 0; i < panes.length; ++i) {
调试代码都删了，其他地方也是

2024-10-24 02:18 UTC, wineee commented on src/utils/helper.cpp
> +                emit choosePane(2);
默认 6 个工作区

2024-10-24 02:29 UTC, wineee commented
请 rebase 并 squash Commits 为一个 commit

commit 信息规范参考[deepin wiki](https://wiki.deepin.org/zh/03_%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83/01_%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83/Commit-%E6%8F%90%E4%BA%A4%E4%BF%A1%E6%81%AF%E8%A7%84%E8%8C%83)

2024-10-24 02:45 UTC, wineee commented on src/qml/HorizontalLayout.qml
> +    function removePane(flag) {
flag 换个名字， removeSurfare 之类

2024-10-24 02:51 UTC, wineee requested changes

2024-10-24 02:51 UTC, wineee commented on src/qml/TiledWorkspace.qml
> +        // let popup = Helper.xdgShellCreator.getIf(popupComponent, finder)
这里不要删

2024-10-24 02:51 UTC, wineee commented on src/qml/TiledWorkspace.qml
> +                item: toplevel,
这个改回来

2024-10-24 02:51 UTC, wineee commented on src/qml/TiledWorkspace.qml
> +        // xdgSurface 是窗口本身
```suggestion
```

2024-10-24 02:57 UTC, wineee requested changes

2024-10-24 02:57 UTC, wineee commented on src/qml/WorkspaceManager.qml
> +        console.log("destory ws")
输出日志使用 LoggingCategory 优化一下
https://doc.qt.io/qt-6/qml-qtqml-loggingcategory.html

2024-10-24 05:57 UTC, LittFlower commented on src/utils/helper.cpp
> +                emit switchLayout();
fixed

2024-10-24 07:20 UTC, wineee commented on src/qml/Main.qml
> +                        active: false
这里是调试用的，最终合并前还是要改成 false

2024-10-24 07:21 UTC, wineee requested changes

2024-10-24 07:21 UTC, wineee commented on src/qml/WorkspaceManager.qml
> +            // console.log(panes)
清理注释

2024-10-24 07:21 UTC, wineee commented on src/qml/WorkspaceManager.qml
> +        // let toPanes = layoutOrder.get(toWsId).panes
清理注释

2024-10-28 06:45 UTC, wineee requested changes

2024-10-28 06:45 UTC, wineee commented on src/treeland.cpp
> +#include "/home/flower/Projects/treeland/build/src/greeter/DisplayManager.h"
这个不要提交上来

2024-10-29 06:54 UTC, wineee approved these changes

2024-10-29 11:12 UTC, merged