chore: release 0.1.0
linuxdeepin/treeland pull request #47
Opened 2023-12-12 05:32 UTC by justforlxz

release 0.1.0

Log:

2023-12-12 05:32 UTC, justforlxz commented
/integrate

2023-12-12 05:37 UTC, BLumia submitted a review, later dismissed

2023-12-12 05:38 UTC, wineee commented
https://github.com/deepin-community/Repository-Integration/pull/760

2023-12-12 05:58 UTC, justforlxz commented
/integrate

2023-12-12 08:39 UTC, justforlxz commented
/integrate

2023-12-13 02:56 UTC, justforlxz commented
/integrate

2023-12-14 02:56 UTC, wineee requested changes

2023-12-14 02:56 UTC, wineee commented on debian/changelog
> + -- rewine <lxz@lxz-PC>  Tue, 12 Dec 2023 13:07:40 +0800
邮箱不对，合并前记得改

2023-12-14 04:27 UTC, justforlxz commented
/integrate

2023-12-14 05:50 UTC, wineee submitted a review, later dismissed

2023-12-18 02:32 UTC, justforlxz commented
/integrate

2023-12-18 14:15 UTC, justforlxz commented
/integrate

2023-12-21 05:46 UTC, justforlxz commented
/integrate

2023-12-21 06:08 UTC, merged

2024-06-24 01:07 UTC, Groveer commented
/help